version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.start
    container_name: djangoProject
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
      - static_data:/app/staticfiles
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db"]
      interval: 5s
      retries: 5
      timeout: 3s
volumes:
  postgres_data:
  static_data: